name: API CI
on:
  push:
    paths:
      - './api/**'
      - '.github/workflows/api-ci.yml'
defaults:
  run:
    working-directory: ./api
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: Install
        shell: bash
        run: npm ci
      - name: Test
        shell: bash
        run: npm run lint
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: Install
        shell: bash
        run: npm ci
      - name: Test
        shell: bash
        run: npm run test
